#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_compute_shader : enable

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (std140, binding = 0) buffer buf {
  uint data[];
};

void main() {
  uint simhash = 1234;
  uint index = (gl_GlobalInvocationID.z * gl_NumWorkGroups.y  +
               gl_GlobalInvocationID.y ) * gl_NumWorkGroups.x +
              gl_GlobalInvocationID.x;
  data[index] = bitCount(data[index] ^ simhash);
}
